# Generated by Django 3.2.13 on 2025-03-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_db_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_new_srs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('project_id', models.IntegerField(default=0)),
            ],
        ),
    ]
