# Generated by Django 3.2.13 on 2025-04-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_db_new_srs'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_projects',
            name='src_case_set',
            field=models.TextField(default=[]),
        ),
    ]
