# Generated by Django 3.2.13 on 2025-09-03 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_db_projects_src_case_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_projects',
            name='old_srs',
            field=models.TextField(default=''),
        ),
    ]
